import { PageSizeType } from '../types/helper';
import React from 'react';

export const pageSize: PageSizeType[] = [
  {
    name: '모바일 세로',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'poster_mb',
    unit: 'px',
  },
  {
    name: 'PC 가로',
    width: 900,
    height: 500,
    icon: null,
    id: 'poster_horizontal',
    unit: 'px',
  },
  {
    name: '공식 계정 이미지',
    width: 900,
    height: 383,
    icon: null,
    id: 'weixin_main',
    unit: 'px',
  },
  {
    name: '공식 계정 보조 이미지',
    width: 500,
    height: 500,
    icon: null,
    id: 'weixin_min',
    unit: 'px',
  },
  {
    name: '샤오홍슈 세로',
    width: 1242,
    height: 1660,
    icon: null,
    id: 'xhs_main',
    unit: 'px',
  },
  {
    name: '긴 이미지',
    width: 1000,
    height: 1500,
    icon: null,
    id: 'article_lang',
    unit: 'px',
  },
  {
    name: 'PPT (16:9)',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'ppt_16_9',
    unit: 'px',
  },
  {
    name: '세로 라이브 배경',
    width: 1242,
    height: 2690,
    icon: null,
    id: 'zhibo_bg',
    unit: 'px',
  },
  {
    name: 'PC 세로 커버',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'video_poster1',
    unit: 'px',
  },
  {
    name: '가로 비디오 커버',
    width: 1920,
    height: 1080,
    icon: null,
    id: 'video_poster2',
    unit: 'px',
  },
  {
    name: '상품 메인 이미지',
    width: 800,
    height: 800,
    icon: null,
    id: 'taobao_main',
    unit: 'px',
  },
  {
    name: '전자상거래 상세 페이지',
    width: 750,
    height: 1000,
    icon: null,
    id: 'taobao_detail',
    unit: 'px',
  },
  {
    name: 'PC 상점 홈',
    width: 1920,
    height: 1500,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '모바일 상점 홈',
    width: 750,
    height: 1000,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '상점 간판',
    width: 1920,
    height: 150,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '전자상거래 가로 포스터',
    width: 750,
    height: 390,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '전자상거래 세로 포스터',
    width: 750,
    height: 950,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '전자상거래 전체 화면 포스터',
    width: 1920,
    height: 700,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '일일 서명',
    width: 1242,
    height: 2208,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '미니 프로그램 커버',
    width: 520,
    height: 416,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: '명함',
    width: 96,
    height: 60,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: '부착 포스터',
    width: 426,
    height: 576,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: '2m 롤업 배너',
    width: 80,
    height: 200,
    icon: null,
    id: '',
    unit: 'cm',
  },
  {
    name: '1.8m 전시 스탠드',
    width: 80,
    height: 180,
    icon: null,
    id: '',
    unit: 'cm',
  },
  {
    name: '쿠폰',
    width: 186,
    height: 66,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: '티켓',
    width: 206,
    height: 86,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: '증명사진',
    width: 25,
    height: 35,
    icon: null,
    id: '',
    unit: 'mm',
  },
];
