const pageData = {
  id: 'SrasKoRnyC',
  name: '빈 페이지',
  desc: '페이지 설명',
  width: 1242,
  height: 2208,
  thumb: '/image/u/9715/uploads/20240418/2c9fda1ade1fac9c11f50ac1632e135eb63ad733.png',
  background: {
    type: 'solid',
    color: '#ffffff',
  },
  layers: [
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '스캔하여 라이브 방송 입장',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 34,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
        strokeWidth: 1,
      },
      id: 'XiSLq8poaiCq7oWs',
      name: '텍스트 요소',
      desc: '설명',
      x: 952,
      y: 2141.1778584392014,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '방송 시간: 11월 11일 20:00',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 55,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: 'A2fz3XeDNvm50_At',
      name: '텍스트 요소',
      desc: '설명',
      x: 290,
      y: 2053,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '다양한 할인 혜택도 있습니다',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 55,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: 'msVgkfavfPBem0Qv',
      name: '텍스트 요소',
      desc: '설명',
      x: 471,
      y: 1976,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '무제한 할인쿠폰',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 55,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: '8NWg5xO7r2j1gIL3',
      name: '텍스트 요소',
      desc: '설명',
      x: 471,
      y: 1898,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL: '',
      text: '라이브\n방송\n한정\n특별\n할인',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: '',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 80,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: '3AWtxaxTiAde6uZt',
      name: '텍스트 요소',
      desc: '설명',
      x: 1109,
      y: 431,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '부터',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 48,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: 'Px0TYsT2S1C0porK',
      name: '텍스트 요소',
      desc: '설명',
      x: 257,
      y: 1134,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93/%E6%80%9D%E6%BA%90%E9%BB%91%E4%BD%93SourceHanSansCN-Medium.otf',
      text: '8折',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 131,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
      },
      id: 'YHS2A5fHP-k7bJuf',
      name: '텍스트 요소',
      desc: '설명',
      x: 52,
      y: 1040,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E8%A3%85%E7%94%B2%E6%98%8E%E6%9C%9D%E4%BD%93/SoukouMincho.ttf',
      text: '더블11 라이브 방송>>',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: '装甲明朝体',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 97,
        fill: 'rgba(245,182,7,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
        },
        lineHeight: {
          value: 150,
          type: 'percent',
        },
        strokeWidth: 1,
      },
      id: '3c6oyl0qfFmPTFH7',
      name: '텍스트 요소',
      desc: '설명',
      x: 45,
      y: 335,
      blur: 0,
      border: {
        stroke: 'rgba(0,0,0,1)',
        strokeWidth: 2,
        visible: false,
      },
      blendMode: 'normal',
      opacity: 1,
      rotation: 0,
      shadow: {
        x: 0,
        y: 0,
        blur: 0,
        color: 'rgba(0,0,0,0.5)',
      },
      _dirty: '1',
      _lock: false,
      _hide: false,
    },
    {
      type: 'text',
      fontFamilyURL:
        'https://h5ds-cdn.oss-cn-beijing.aliyuncs.com/static/fonts/%E8%A3%85%E7%94%B2%E6%98%8E%E6%9C%9D%E4%BD%93/SoukouMincho.ttf',
      text: 'LOGO',
      fill: '',
      textStyle: {
        textDecoration: 'normal',
        textAlign: 'left',
        fontFamily: '装甲明朝体',
        fontWeight: 'normal',
        fontStyle: 'normal',
        fontSize: 97,
        fill: 'rgba(255,255,255,1)',
        letterSpacing: {
          value: 0,
          type: 'percent',
          lineHeight: {
            value: 150,
            type: 'percent',
          },
        },
        id: 'nWDwaOk9QtXjv2hB',
        name: '텍스트 요소',
        desc: '설명',
        x: 45,
        y: 196,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.5)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
      },
      {
        type: 'image',
        width: 224,
        height: 224,
        flipx: false,
        flipy: false,
        cropSize: null,
        url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_6.png',
        cornerRadius: [0, 0, 0, 0],
        id: 'U7SU9uC-2JL6o9JM',
        name: '이미지 요소',
        desc: '설명 정보',
        x: 958,
        y: 1896,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.0)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
        naturalHeight: 224,
        naturalWidth: 224,
        _ratio: 1,
      },
      {
        type: 'image',
        width: 330,
        height: 330,
        flipx: false,
        flipy: false,
        cropSize: null,
        url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_4.png',
        cornerRadius: [0, 0, 0, 0],
        id: 'QVXvhYoR3KcLZXle',
        name: '이미지 요소',
        desc: '설명 정보',
        x: 18,
        y: 976,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.0)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
        naturalHeight: 330,
        naturalWidth: 330,
      },
      {
        type: 'image',
        width: 1099,
        height: 1596,
        flipx: false,
        flipy: false,
        cropSize: null,
        url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_3.png',
        cornerRadius: [0, 0, 0, 0],
        id: 'm96ihMaL-7aYbCUq',
        name: '이미지 요소',
        desc: '설명 정보',
        x: -29,
        y: 116,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.0)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
        naturalHeight: 1596,
        naturalWidth: 1099,
      },
      {
        type: 'image',
        width: 1165,
        height: 1560,
        flipx: false,
        flipy: false,
        cropSize: null,
        url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_2.png',
        cornerRadius: [0, 0, 0, 0],
        id: 'vpjNGKwukQrKTNXh',
        name: '이미지 요소',
        desc: '설명 정보',
        x: -120,
        y: 128,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.0)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
        naturalHeight: 1560,
        naturalWidth: 1165,
      },
      {
        type: 'image',
        width: 1242,
        height: 2208,
        flipx: false,
        flipy: false,
        cropSize: null,
        url: 'https://cdn.h5ds.com/psd_layers/u/9218/20201110/1605001077920_layer_1.png',
        cornerRadius: [0, 0, 0, 0],
        id: 'ydh4IYJzQ2i800v7',
        name: '이미지 요소',
        desc: '설명 정보',
        x: 0,
        y: 0,
        blur: 0,
        border: {
          stroke: 'rgba(0,0,0,1)',
          strokeWidth: 2,
          visible: false,
        },
        blendMode: 'normal',
        opacity: 1,
        rotation: 0,
        shadow: {
          x: 0,
          y: 0,
          blur: 0,
          color: 'rgba(0,0,0,0.0)',
        },
        _dirty: '1',
        _lock: false,
        _hide: false,
        naturalHeight: 2208,
        naturalWidth: 1242,
      },
    ],
  };